// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecuteSql.proto

// Protobuf Java Version: 3.25.5
package cn.ac.iscas.dmo.db.rpc.execute;

public interface ConnectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ac.iscas.dmo.db.rpc.stream.ConnectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string datasourceType = 1;</code>
   * @return The datasourceType.
   */
  String getDatasourceType();
  /**
   * <code>string datasourceType = 1;</code>
   * @return The bytes for datasourceType.
   */
  com.google.protobuf.ByteString
      getDatasourceTypeBytes();

  /**
   * <code>string datasourceName = 2;</code>
   * @return The datasourceName.
   */
  String getDatasourceName();
  /**
   * <code>string datasourceName = 2;</code>
   * @return The bytes for datasourceName.
   */
  com.google.protobuf.ByteString
      getDatasourceNameBytes();

  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  String getUsername();
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 4;</code>
   * @return The password.
   */
  String getPassword();
  /**
   * <code>string password = 4;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
