// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecuteSql.proto

// Protobuf Java Version: 3.25.5
package cn.ac.iscas.dmo.db.rpc.execute;

/**
 * Protobuf type {@code cn.ac.iscas.dmo.db.rpc.stream.ExecuteRequest}
 */
public final class ExecuteRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.ac.iscas.dmo.db.rpc.stream.ExecuteRequest)
    ExecuteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecuteRequest.newBuilder() to construct.
  private ExecuteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteRequest() {
    datasourceType_ = "";
    datasourceName_ = "";
    sql_ = "";
    token_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecuteRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ExecuteSql.internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ExecuteSql.internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ExecuteRequest.class, Builder.class);
  }

  public static final int DATASOURCETYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object datasourceType_ = "";
  /**
   * <code>string datasourceType = 1;</code>
   * @return The datasourceType.
   */
  @Override
  public String getDatasourceType() {
    Object ref = datasourceType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      datasourceType_ = s;
      return s;
    }
  }
  /**
   * <code>string datasourceType = 1;</code>
   * @return The bytes for datasourceType.
   */
  @Override
  public com.google.protobuf.ByteString
      getDatasourceTypeBytes() {
    Object ref = datasourceType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      datasourceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATASOURCENAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object datasourceName_ = "";
  /**
   * <code>string datasourceName = 2;</code>
   * @return The datasourceName.
   */
  @Override
  public String getDatasourceName() {
    Object ref = datasourceName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      datasourceName_ = s;
      return s;
    }
  }
  /**
   * <code>string datasourceName = 2;</code>
   * @return The bytes for datasourceName.
   */
  @Override
  public com.google.protobuf.ByteString
      getDatasourceNameBytes() {
    Object ref = datasourceName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      datasourceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SQL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object sql_ = "";
  /**
   * <code>string sql = 3;</code>
   * @return The sql.
   */
  @Override
  public String getSql() {
    Object ref = sql_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sql_ = s;
      return s;
    }
  }
  /**
   * <code>string sql = 3;</code>
   * @return The bytes for sql.
   */
  @Override
  public com.google.protobuf.ByteString
      getSqlBytes() {
    Object ref = sql_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sql_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object token_ = "";
  /**
   * <code>string token = 4;</code>
   * @return The token.
   */
  @Override
  public String getToken() {
    Object ref = token_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <code>string token = 4;</code>
   * @return The bytes for token.
   */
  @Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    Object ref = token_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(datasourceType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, datasourceType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(datasourceName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, datasourceName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sql_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sql_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, token_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(datasourceType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, datasourceType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(datasourceName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, datasourceName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sql_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sql_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, token_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ExecuteRequest)) {
      return super.equals(obj);
    }
    ExecuteRequest other = (ExecuteRequest) obj;

    if (!getDatasourceType()
        .equals(other.getDatasourceType())) return false;
    if (!getDatasourceName()
        .equals(other.getDatasourceName())) return false;
    if (!getSql()
        .equals(other.getSql())) return false;
    if (!getToken()
        .equals(other.getToken())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATASOURCETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDatasourceType().hashCode();
    hash = (37 * hash) + DATASOURCENAME_FIELD_NUMBER;
    hash = (53 * hash) + getDatasourceName().hashCode();
    hash = (37 * hash) + SQL_FIELD_NUMBER;
    hash = (53 * hash) + getSql().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ExecuteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExecuteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExecuteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExecuteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExecuteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExecuteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExecuteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExecuteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ExecuteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ExecuteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ExecuteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.ac.iscas.dmo.db.rpc.stream.ExecuteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.ac.iscas.dmo.db.rpc.stream.ExecuteRequest)
      ExecuteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExecuteSql.internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExecuteSql.internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExecuteRequest.class, Builder.class);
    }

    // Construct using cn.ac.iscas.dmo.db.rpc.execute.ExecuteRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      datasourceType_ = "";
      datasourceName_ = "";
      sql_ = "";
      token_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ExecuteSql.internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteRequest_descriptor;
    }

    @Override
    public ExecuteRequest getDefaultInstanceForType() {
      return ExecuteRequest.getDefaultInstance();
    }

    @Override
    public ExecuteRequest build() {
      ExecuteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ExecuteRequest buildPartial() {
      ExecuteRequest result = new ExecuteRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ExecuteRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.datasourceType_ = datasourceType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.datasourceName_ = datasourceName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sql_ = sql_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.token_ = token_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ExecuteRequest) {
        return mergeFrom((ExecuteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ExecuteRequest other) {
      if (other == ExecuteRequest.getDefaultInstance()) return this;
      if (!other.getDatasourceType().isEmpty()) {
        datasourceType_ = other.datasourceType_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDatasourceName().isEmpty()) {
        datasourceName_ = other.datasourceName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSql().isEmpty()) {
        sql_ = other.sql_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              datasourceType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              datasourceName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              sql_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              token_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object datasourceType_ = "";
    /**
     * <code>string datasourceType = 1;</code>
     * @return The datasourceType.
     */
    public String getDatasourceType() {
      Object ref = datasourceType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        datasourceType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string datasourceType = 1;</code>
     * @return The bytes for datasourceType.
     */
    public com.google.protobuf.ByteString
        getDatasourceTypeBytes() {
      Object ref = datasourceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        datasourceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string datasourceType = 1;</code>
     * @param value The datasourceType to set.
     * @return This builder for chaining.
     */
    public Builder setDatasourceType(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      datasourceType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string datasourceType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDatasourceType() {
      datasourceType_ = getDefaultInstance().getDatasourceType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string datasourceType = 1;</code>
     * @param value The bytes for datasourceType to set.
     * @return This builder for chaining.
     */
    public Builder setDatasourceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      datasourceType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object datasourceName_ = "";
    /**
     * <code>string datasourceName = 2;</code>
     * @return The datasourceName.
     */
    public String getDatasourceName() {
      Object ref = datasourceName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        datasourceName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string datasourceName = 2;</code>
     * @return The bytes for datasourceName.
     */
    public com.google.protobuf.ByteString
        getDatasourceNameBytes() {
      Object ref = datasourceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        datasourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string datasourceName = 2;</code>
     * @param value The datasourceName to set.
     * @return This builder for chaining.
     */
    public Builder setDatasourceName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      datasourceName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string datasourceName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDatasourceName() {
      datasourceName_ = getDefaultInstance().getDatasourceName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string datasourceName = 2;</code>
     * @param value The bytes for datasourceName to set.
     * @return This builder for chaining.
     */
    public Builder setDatasourceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      datasourceName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object sql_ = "";
    /**
     * <code>string sql = 3;</code>
     * @return The sql.
     */
    public String getSql() {
      Object ref = sql_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sql_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sql = 3;</code>
     * @return The bytes for sql.
     */
    public com.google.protobuf.ByteString
        getSqlBytes() {
      Object ref = sql_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sql_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sql = 3;</code>
     * @param value The sql to set.
     * @return This builder for chaining.
     */
    public Builder setSql(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      sql_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string sql = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSql() {
      sql_ = getDefaultInstance().getSql();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string sql = 3;</code>
     * @param value The bytes for sql to set.
     * @return This builder for chaining.
     */
    public Builder setSqlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sql_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private Object token_ = "";
    /**
     * <code>string token = 4;</code>
     * @return The token.
     */
    public String getToken() {
      Object ref = token_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string token = 4;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string token = 4;</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      token_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string token = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      token_ = getDefaultInstance().getToken();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string token = 4;</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      token_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.ac.iscas.dmo.db.rpc.stream.ExecuteRequest)
  }

  // @@protoc_insertion_point(class_scope:cn.ac.iscas.dmo.db.rpc.stream.ExecuteRequest)
  private static final ExecuteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExecuteRequest();
  }

  public static ExecuteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteRequest>() {
    @Override
    public ExecuteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecuteRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ExecuteRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public ExecuteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

