// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecuteSql.proto

// Protobuf Java Version: 3.25.5
package cn.ac.iscas.dmo.db.rpc.execute;

public final class ExecuteSql {
  private ExecuteSql() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020ExecuteSql.proto\022\035cn.ac.iscas.dmo.db.r" +
      "pc.stream\"\\\n\016ExecuteRequest\022\026\n\016datasourc" +
      "eType\030\001 \001(\t\022\026\n\016datasourceName\030\002 \001(\t\022\013\n\003s" +
      "ql\030\003 \001(\t\022\r\n\005token\030\004 \001(\t\">\n\017ExecuteRespon" +
      "se\022\016\n\006status\030\001 \001(\005\022\014\n\004data\030\002 \001(\014\022\r\n\005erro" +
      "r\030\003 \001(\t2}\n\rStreamService\022l\n\007execute\022-.cn" +
      ".ac.iscas.dmo.db.rpc.stream.ExecuteReque" +
      "st\032..cn.ac.iscas.dmo.db.rpc.stream.Execu" +
      "teResponse\"\0000\001B.\n\036cn.ac.iscas.dmo.db.rpc" +
      ".executeB\nExecuteSqlP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteRequest_descriptor,
        new String[] { "DatasourceType", "DatasourceName", "Sql", "Token", });
    internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_ac_iscas_dmo_db_rpc_stream_ExecuteResponse_descriptor,
        new String[] { "Status", "Data", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
