// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecuteSql.proto

// Protobuf Java Version: 3.25.5
package cn.ac.iscas.dmo.db.rpc.execute;

public interface ExecuteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.ac.iscas.dmo.db.rpc.stream.ExecuteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string datasourceType = 1;</code>
   * @return The datasourceType.
   */
  String getDatasourceType();
  /**
   * <code>string datasourceType = 1;</code>
   * @return The bytes for datasourceType.
   */
  com.google.protobuf.ByteString
      getDatasourceTypeBytes();

  /**
   * <code>string datasourceName = 2;</code>
   * @return The datasourceName.
   */
  String getDatasourceName();
  /**
   * <code>string datasourceName = 2;</code>
   * @return The bytes for datasourceName.
   */
  com.google.protobuf.ByteString
      getDatasourceNameBytes();

  /**
   * <code>string sql = 3;</code>
   * @return The sql.
   */
  String getSql();
  /**
   * <code>string sql = 3;</code>
   * @return The bytes for sql.
   */
  com.google.protobuf.ByteString
      getSqlBytes();

  /**
   * <code>string token = 4;</code>
   * @return The token.
   */
  String getToken();
  /**
   * <code>string token = 4;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
